accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
]

project_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("", include("accounts.urls")),
]

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path("", views.home, name="home"),
    path("change_status/<int:pk>/", views.change_status, name="change_status"),
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Todo(models.Model):
    STATUS_CHOICES = {
        1: "In Progress",
        2: "Done",
    }
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    status = models.IntegerField(default=1, choices=STATUS_CHOICES)
    date_time = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

todo/forms.py
from django.forms import ModelForm

from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["content"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"{username} register successfully.")
            return redirect("todo:home")

    else:
        form = RegisterForm()

    context = {"form": form}

    return render(request, "accounts/register.html", context)

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from .forms import TodoForm
from .models import Todo


# Create your views here.
@login_required
def home(request):
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            # messages.success(request, "Todo Added!")
            return redirect("todo:home")
    else:
        form = TodoForm()

    todos = Todo.objects.filter(user=request.user).order_by("-date_time")

    context = {
        "form": form,
        "todos": todos,
        "title": "Home",
    }

    return render(request, "todo/index.html", context)


@login_required
def change_status(request, pk):
    todo = get_object_or_404(Todo, pk=pk)

    if todo.status == 1:
        todo.status = 2
        todo.save()
    elif todo.status == 2:
        todo.delete()
        messages.success(request, f"Pwoshhh.....{todo.content} deleted")
    return redirect("todo:home")

accounts/templates/accounts/login.html
{% extends "todo/base.html" %}
{% load crispy_forms_tags %}

{% block main %}

<div class="container mt-5">
    <div class="container m-4">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            <form action="" method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </fieldset>
    </div>
</div>

<div class="container my-5">
    <p>Need an account ? <a href="{% url 'accounts:register' %}">Register Here!</a></p>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends "todo/base.html" %}

{% block main %}
<h3>Log Out</h3>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "todo/base.html" %}
{% load crispy_forms_tags %}

{% block main %}
<div class="container mt-5">
    <div class="container m-4">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add New Account</legend>
            <form action="" method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </fieldset>
    </div>
</div>


{% endblock %}

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todo/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% if title %}
    <title>Todo - {{ title }}</title>
    {% else %}
    <title>Todo</title>
    {% endif %}
</head>

<body style="background-color: #181d25;">

    {% include "todo/nav.html" %}
    <!-- flash message -->
    <div class="container">
        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-dark" role="alert">{{ msg }}</div>
        {% endfor %}
        {% endif %}
    </div>

    <div class="container px-4 py-2 my-5" style="background-color: rgb(111, 126, 126);">
        {% block main %}
        {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>

</html>

todo/templates/todo/index.html
{% extends "todo/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}

<div class="container my-5">

    <table class="table">
        <thead>
            <tr class="table-info">
                <th scope="col">#</th>
                <th scope="col">Date/Time</th>
                <th scope="col">Content</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ todo.date_time|date:"D jMy | g:iA" }}</td>
                <td>{{ todo.content }}</td>
                {% if todo.status == 1 %}
                <td class="table-danger text-center">
                    <a class="btn btn-outline-danger btn-sm" href="{% url 'todo:change_status' todo.pk %}">
                        {{ todo.get_status_display }}
                    </a>
                </td>
                {% else %}
                <td class="table-success text-center">
                    <a class="btn btn-outline-success btn-sm" href="{% url 'todo:change_status' todo.pk %}">
                        {{ todo.get_status_display }}
                    </a>
                </td>
                {% endif %}
            </tr>
            {% empty %}
            <tr>
                <td></td>
                <td></td>
                <td>
                    <p class="fst-italic">Congratulations!! You don't have any pending Todos.</p>
                </td>
                <td></td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>

<div class="container mt-5">
    <div class="container m-4">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"><img src="{% static 'todo/reading.png' %}" width="50" height="50"
                    alt="cat reading">Add Todo</legend>
            <form action="" method="post">
                <div class="mb-3">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </fieldset>
    </div>
</div>

{% endblock %}

todo/templates/todo/nav.html
{% load static %}

<nav class="navbar bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todo:home' %}">
            <img src="{% static 'todo/checklist.png' %}" alt="Logo" width="30" height="24"
                class="d-inline-block align-text-top">
            <em>Todo</em>
        </a>
        {% if user.is_authenticated %}
        <p class="text-white">Hello {{ user.username }}</p>
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Log Out</button>
        </form>
        {% else %}
        <a class="btn btn-sm btn-outline-light" href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
    </div>
</nav>